INSERT INTO PROFESORES (NOMBRE, APELLIDO, MATERIA) VALUES ('Juan', 'Díaz Sánchez', 'Matemáticas');
INSERT INTO PROFESORES (NOMBRE, APELLIDO, MATERIA) VALUES ('Rosa', 'Pérez Duarte', 'Geografía');

INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Sandra', 'Muñoz Gil', '1º Primaria');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Lucio', 'Laureano Martínez', '1º Primaria');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Pedro', 'Camacho Cobo', '2º Primaria');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Cristina', 'Romero Encina', '2º Primaria');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Luisa', 'Domínguez Solís', '3º Primaria');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO, CURSO) VALUES ('Ramón', 'Rodríguez Gil', '3º Primaria');

INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (1, 1);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (1, 2);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (1, 5);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (1, 6);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (2, 3);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (2, 4);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (2, 5);
INSERT INTO PROFESORES_ALUMNOS (ID_PROFESOR, ID_ALUMNO) VALUES (2, 6);