CREATE TABLE PROFESORES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	MATERIA VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ALUMNOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CURSO VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE PROFESORES_ALUMNOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ID_PROFESOR INTEGER NOT NULL,
	ID_ALUMNO INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE PROFESORES_ALUMNOS ADD FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID);
ALTER TABLE PROFESORES_ALUMNOS ADD FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID);
	